apiVersion: 1

datasources:
  - name: K6InfluxDB
    type: influxdb
    access: proxy
    database: scripts
    url: http://influxdb:8086
    isDefault: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
